services:
  - type: web
    name: cryptosphere-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        value: your_botfather_token
      - key: GROUP_CHAT_ID
        value: -100xxxxxxxxxx
      - key: PAYSTACK_SECRET
        value: your_webhook_secret
